[mysqld]
user = mysql
pid-file = /run/mysqld/mysqld.pid
socket = /run/mysqld/mysqld.sock
basedir = /usr
port = 3306
datadir = /var/lib/mysql
tmpdir = /tmp
query_cache_size = 16M
bind_address=*
log_error = /var/log/mysql/mariadb_error.log