CREATE DATABASE Base;
CREATE USER $MYSQL_USER@'%' IDENTIFIED BY '$MYSQL_PWD';
GRANT ALL PRIVILEGES ON Bases.* TO $MYSQL_USER@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PWD'